backend:
  name: github
  repo: nikejesstwtw/nikejesstwtw.github.io # 請確認這裡的帳號和倉庫名稱與您的一致
  branch: main # 主要分支名稱
  auth_type: "implicit"
  app_id: "YOUR_APP_ID" # 請貼上您在步驟三從 GitHub 取得的 Client ID

media_folder: "assets/uploads" # 上傳的圖片會儲存在這裡
public_folder: "/assets/uploads" # 網站讀取圖片的路徑

collections:
  - name: "posts" # 內容類型的內部名稱
    label: "文章" # 顯示在後台的名稱
    folder: "_posts" # 儲存文章檔案的資料夾
    create: true # 允許在後台新增文章
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文章檔案的命名規則
    fields: # 定義後台編輯器中的欄位
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "分類", name: "category", widget: "select", options: ["好物推薦", "育兒生活", "生活隨筆"] }
      - { label: "特色圖片", name: "thumbnail", widget: "image", required: false }
      - { label: "內文", name: "body", widget: "markdown" }
