backend:
  name: github
  repo: nikejesstwtw/nikejesstwtw.github.io
  branch: main
  auth_type: "implicit"
  app_id: "Ov23liZ9mXivSY1ktVjV" # 請務必將這裡換成您自己的 GitHub Client ID

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "分類", name: "category", widget: "select", options: ["好物推薦", "育兒生活", "生活隨筆"] }
      - { label: "特色圖片", name: "thumbnail", widget: "image", required: false }
      - { label: "內文", name: "body", widget: "markdown" }
