# This backend configuration uses Netlify's Git Gateway for seamless authentication.
backend:
  name: git-gateway
  branch: main # The branch to update

# The media folder and public folder are relative to the root of the repository
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# This is where the blog posts will be stored
collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "分類", name: "category", widget: "select", options: ["好物推薦", "育兒生活", "生活隨筆"] }
      - { label: "特色圖片", name: "thumbnail", widget: "image", required: false }
      - { label: "內文", name: "body", widget: "markdown" }
